
#!/bin/sh
source config.sh

#dns config
echo 'modify dns config'
sudo cat << eof > /etc/NetworkManager/NetworkManager.conf
[main]
plugins=ifcfg-rh
dns=none

[logging]
#level=DEBUG
#domains=ALL
eof

sudo systemctl restart NetworkManager.service
sudo cat << eof > /etc/resolv.conf
# Generated by NetworkManager
search $domain
nameserver $dns_host
eof
