version: '3'

services:
  namenode:
    image: 'uhopper/hadoop-namenode'
    container_name: namenode
    domainname: hadoop
    hostname: namenode
    ports:
      - "8020:8020"
      - '50070:50070'
    #net: hadoop
    volumes:
      - /mnt/docker/name:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=sandbox
      - HDFS_CONF_dfs_replication=1

  datanode:
    image: "uhopper/hadoop-datanode"
    container_name: datanode
    domainname: hadoop
    hostname: datanode
    #net: hadoop
    volumes:
      - /mnt/docker/data:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CLUSTER_NAME=sandbox
      - HDFS_CONF_dfs_replication=1
    depends_on:
      - "namenode"

networks:
    default:
        external:
            name: sandbox-cluster