version: '3'

services:
  namenode:
    image: 'uhopper/hadoop-namenode'
    #container_name: namenode
    #domainname: data.com
    hostname: namenode
    env_file: config.sh

    ports:
      - "8020:8020"
      - '50070:50070'
    volumes:
      - $NAME_HOME:$NAME_DEST
    environment:
      - NOTHING


networks:
  default:
    external:
      name: "hadoop-network"