{
 "title": "my first11",
 "description": "the first one",
 "tags": [ "bbc_tags" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "vtest" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Counter -> histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(test_counter_speed[10s]))  by (works)"
    }
   ]
  },
  {
   "title": "histogram",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_latency_seconds_bucket"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Counter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "test_counter_speed" },
    {}
   ]
  },
  {
   "title": "Counter",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(test_counter_speed{speed=\"server-1\"}[10s])"
    }
   ]
  },
  { "title": "Panel Title", "type": "dashlist", "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Counter rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "sdfsdfdsfsd" }
   ],
   "targets": [
    { "expr": "rate(test_counter_speed[5m])" },
    {}
   ]
  }
 ]
}